* highlight-selection
#+BEGIN_QUOTE
Yet another attempt to bring highlight selection to emacs.
#+END_QUOTE
Unlike other attempts, that highlight symbol-at-point using an idle
timer, this program advises `mouse-drag-region' to highlight
current selection, that means that user will be able to
double-click a word, or manually section a symbol, then all
occurrences of that word/symbol will be highlighted. The highlight
will be remove when user select a blank space or new line.

Works best with ~evil-search~.
* Example:
- Select a word to highlight
- Double-click to highlight
- Double-click beyond end of line to remove highlight
* Installation
Remove =:load-path= if the package is installed via =package.el=
#+BEGIN_SRC emacs-lisp
(require 'use-package)
(use-package highlight-selection
  :load-path "/path/to/highlight-selection/"
  :diminish highlight-selection-mode
  :demand
  :config (highlight-selection-mode 1)
  :bind (("s-e" . highlight-selection-current-selection)))
#+END_SRC

* License
MIT
#+BEGIN_QUOTE
Copyright (c) 2015 Quang-Linh LE

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+END_QUOTE
